/*jslint node: true*/

var recoveryEmail = function (username, password) {
    'use strict';
    return "<style>" +
        "body {" +
        "padding: 5%;" +
        "background: #DDD;" +
        "font-family: 'Ubuntu', sans-serif;" +
        "}" +
        "h3 {" +
        "color: #511;" +
        "}" +
        "span {" +
        "color: #115;" +
        "font-size: 115%;" +
        "}" +
        "</style>" +
        "<h2>&#127939; Altamonte Springs Wellness App &#127939;</h2>" +
        "<h3>Account recovery instructions</h3>" +
        "<p>A temporary password has been created for your account. Use the login credentials below to gain access to your account. Once you have successfully logged in, you will be asked to change your password.</p>" +
        "<p><strong>username: </strong><span>" + username + "</span><br><strong>password: </strong><span>" + password + "</span></p>" +
        "<hr>" +
        "<p>&#129302; <em>This email was generated by an email bot! You may reply to it if you wish, but the email bot does not know how to read...it only knows how to send emails.</em> &#129302;</p>";
};

module.exports = recoveryEmail;